# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      apt install rsync
      chmod 400 keys/id_rsa
      pip install matplotlib scikit-learn
      pip install -r requirements.txt
      pip install torch==1.7.1+cpu torchvision==0.8.2+cpu -f https://download.pytorch.org/whl/torch_stable.html
      export PATH=$PATH:~/.local/bin
      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    command: echo 'start script'
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 7071
    onOpen: open-preview